---
mode: required
method: legacy
labels:
    step: "Choose DE"

items:
    - id: kde
      name: "KDE Plasma"
      description: "Современный и настраиваемый рабочий стол, подойдет перешедшим с Windows."
      screenshot: "/etc/calamares/images/kde.png"
      packages: [plasma-desktop, sddm] # Что проверить/доставить
    - id: gnome
      name: "GNOME"
      description: "Простой и интуитивный интерфейс."
      screenshot: "/etc/calamares/images/gnome.png"
      packages: [gnome-shell, gdm]
